spring.application.name=LibraryProject-1
spring.datasource.url=jdbc:mysql://localhost:3306/db
spring.datasource.username=root
spring.datasource.password=Siva@1509
spring.jpa.hibernate.ddl-auto=update
jwt.secret=CEjIiQH0PO5UnsEv89cE3owBmMNtcMRzHS2Ih4wvMhU=


